#!/bin/bash

# version 20171018-1018

#
# Files listing in human readable form
#
alias ll="ls -lh --color=auto"
alias la="ll -a"

#
# Calendar
#
# First day of week to be Monday
#
alias cal="cal -m"

#
# Volume
#
STEP=10
alias volu="amixer set Master $STEP%+"
alias vold="amixer set Master $STEP%-"

#
# SSH
#
alias ssh-magic="ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

#
# Arch Linux
#
# alias pacman-db-update="pacman -Syy"
