#!/bin/bash

echo "Archy Install (c) 2017"
echo "-----------------------"

USER_DIR="$(eval echo ~$USER)"
DIR="$USER_DIR/.archy"

echo "Running directory: $(pwd)"
echo "User directory: $USER_DIR"

BASHRC_SOURCE="$(pwd)/.bashrc"
BASHRC_TARGET="$USER_DIR/.bashrc"

if [ ! -L $BASHRC_TARGET ]; then
    echo ".bashrc is a regular file."
    cp $BASHRC_TARGET "$USER_DIR/.bashrc.backup"
    rm $BASHRC_TARGET
    echo ".bashrc was backed up in .bashrc.backup"
    echo "Creating link for .bashrc..."
    ln -s $BASHRC_SOURCE $BASHRC_TARGET
else
    echo ".bashrc is already a link."
fi

echo "Starting script check-dir..."
$(pwd)/check-dir

SOURCE_ALIASES="$(pwd)/aliases"
TARGET_ALIASES="$DIR/aliases"

if [ ! -f $TARGET_ALIASES ]; then
    echo "Creating link for aliases..."
    ln -s $SOURCE_ALIASES $TARGET_ALIASES
else
    echo "Link for aliases already exists."
fi

